package com.cts.userservice.security.filter;

import com.cts.userservice.security.JwtUtil;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.List;

/**
 * Servlet filter that authenticates requests carrying a JWT bearer token.
 *
 * <p>Extends {@link OncePerRequestFilter} so it runs at most once per request.
 * It inspects the {@code Authorization} header for a {@code Bearer} token and,
 * when the token is valid, populates the Spring Security context with an
 * {@link UsernamePasswordAuthenticationToken} carrying the user id as the
 * principal and the token's role as a granted authority (prefixed with
 * {@code ROLE_}). Requests without a valid token pass through unauthenticated,
 * leaving authorization decisions to the security configuration.</p>
 *
 * <p>Registered as a Spring {@link Component}; the {@link JwtUtil} dependency is
 * injected via the constructor generated by Lombok's
 * {@code @RequiredArgsConstructor}.</p>
 */
@Component
@RequiredArgsConstructor
public class JwtAuthFilter extends OncePerRequestFilter {

    /** Utility used to validate tokens and extract their claims. */
    private final JwtUtil jwtUtil;

    /**
     * Authenticates the request from its bearer token, if present and valid,
     * then continues the filter chain.
     *
     * <p>If the {@code Authorization} header holds a valid {@code Bearer} token,
     * the user id and role are extracted and stored in the
     * {@link SecurityContextHolder}. The chain proceeds regardless, so missing
     * or invalid tokens simply leave the request unauthenticated.</p>
     *
     * @param request     the incoming HTTP request
     * @param response    the HTTP response
     * @param filterChain the remaining filter chain to delegate to
     * @throws ServletException if the downstream chain raises a servlet error
     * @throws IOException      if an I/O error occurs during processing
     */
    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain)
            throws ServletException, IOException {

        String header = request.getHeader("Authorization");

        if (header != null && header.startsWith("Bearer ")) {

            String token = header.substring(7);

            if (jwtUtil.isTokenValid(token)) {

                String userId = jwtUtil.extractUserId(token);
                String role = jwtUtil.extractRole(token);

                var auth = new UsernamePasswordAuthenticationToken(
                        userId,
                        null,
                        List.of(new SimpleGrantedAuthority("ROLE_" + role))
                );

                SecurityContextHolder.getContext().setAuthentication(auth);
            }
        }

        filterChain.doFilter(request, response);
    }
}