package com.cts.review.exception;

import com.cts.review.exception.customexception.InvalidReviewException;
import com.cts.review.exception.customexception.ReviewNotFoundException;
import com.cts.review.exception.customexception.ReviewOperationException;
import com.cts.review.exception.feignclientexception.CatalogServiceDownException;
import jakarta.servlet.http.HttpServletRequest;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.support.DefaultMessageSourceResolvable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.MissingRequestHeaderException;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDateTime;
import java.util.Map;


/**
 * Global exception handler for the Review Service.
*/
@Slf4j
@RestControllerAdvice
public class GlobalExceptionHandler {


    /**
     * Handles cases where a review is not found.
     *
     * @param ex the exception thrown
     * @return standardized error response with HTTP 404
     */
    @ExceptionHandler(ReviewNotFoundException.class)
    public ResponseEntity<ErrorResponse> handleNotFound(ReviewNotFoundException ex) {
        return new ResponseEntity<>(
                buildError(ex.getMessage(), HttpStatus.NOT_FOUND),
                HttpStatus.NOT_FOUND
        );
    }


    /**
     * Handles invalid review input scenarios.
     *
     * @param ex the exception thrown
     * @return standardized error response with HTTP 400
     */
    @ExceptionHandler(InvalidReviewException.class)
    public ResponseEntity<ErrorResponse> handleInvalid(InvalidReviewException ex) {
        return new ResponseEntity<>(
                buildError(ex.getMessage(), HttpStatus.BAD_REQUEST),
                HttpStatus.BAD_REQUEST
        );
    }


    /**
     * Handles business-level failures during review operations.
     *
     * @param ex the exception thrown
     * @return standardized error response with HTTP 500
     */
    @ExceptionHandler(ReviewOperationException.class)
    public ResponseEntity<ErrorResponse> handleOperation(ReviewOperationException ex) {
        return new ResponseEntity<>(
                buildError(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR),
                HttpStatus.INTERNAL_SERVER_ERROR
        );
    }


    /**
     * Handles failures related to communication with the Catalog Service.
     *
     * @param ex  the exception thrown
     * @param req HTTP request details
     * @return standardized error response with HTTP 503
     */
    @ExceptionHandler(CatalogServiceDownException.class)
    public ResponseEntity<ErrorResponse> handleCatalogDown(
            CatalogServiceDownException ex,
            HttpServletRequest req) {

        log.error("Catalog service failure", ex);

        return new ResponseEntity<>(buildError(
                ex.getMessage(),
                HttpStatus.SERVICE_UNAVAILABLE), HttpStatus.SERVICE_UNAVAILABLE);
    }

    /**
     * Handles exceptions generated by missing header
     * @param ex the exception thrown
     * @return standardized error response with HTTP 400
     */
    @ExceptionHandler(MissingRequestHeaderException.class)
    public ResponseEntity<ErrorResponse> handleMissingHeader(MissingRequestHeaderException ex) {
        return new ResponseEntity<>(
                buildError("Missing required header: " + ex.getHeaderName(), HttpStatus.BAD_REQUEST),
                HttpStatus.BAD_REQUEST
        );
    }


    /**
     * Handles validation failures triggered by @Valid annotation.
     *
     * Captures field-level validation errors and returns a standardized
     * error response with HTTP 400 status.
     *
     * @param ex exception containing validation errors
     * @return error response with validation message
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handleValidation(MethodArgumentNotValidException ex) {

        String message = ex.getBindingResult()
                .getFieldErrors()
                .stream()
                .map(DefaultMessageSourceResolvable::getDefaultMessage)
                .findFirst()
                .orElse("Validation failed");

        return new ResponseEntity<>(
                buildError(message, HttpStatus.BAD_REQUEST),
                HttpStatus.BAD_REQUEST
        );
    }




    /**
     * Handles all uncaught exceptions (fallback handler).
     *
     * @param ex the exception thrown
     * @return standardized error response with HTTP 500
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleGeneric(Exception ex) {
        return new ResponseEntity<>(
                buildError("Unexpected error occurred", HttpStatus.INTERNAL_SERVER_ERROR),
                HttpStatus.INTERNAL_SERVER_ERROR
        );
    }


    /**
     * Builds a standardized {@link ErrorResponse}.
     *
     * @param message error message
     * @param status  HTTP status
     * @return populated ErrorResponse object
     */
    private ErrorResponse buildError(String message, HttpStatus status) {
        return new ErrorResponse(
                LocalDateTime.now(),
                status.value(),
                status.getReasonPhrase(),
                message
        );
    }
}
