package com.cts.userservice.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

import lombok.*;
/**
 * JPA entity holding the authentication credentials for a {@link User}.
 *
 * <p>Mapped to the {@code authentication} table and separated from the
 * {@link User} entity so that sensitive credential data lives in its own
 * table. This is the owning side of a one-to-one relationship with
 * {@link User}: it carries the {@code user_id} foreign key, which is both
 * non-null and unique, enforcing exactly one credentials row per user.</p>
 *
 * <p>Lombok's {@code @Data} generates getters, setters, {@code equals},
 * {@code hashCode}, and {@code toString}; {@code @NoArgsConstructor} and
 * {@code @AllArgsConstructor} generate constructors (the no-arg constructor is
 * required by JPA); and {@code @Builder} provides a fluent builder.</p>
 *
 */
@Entity
@Table(name = "authentication")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Authentication {

    /**
     * Surrogate primary key, auto-generated by the database identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "auth_id")
    private Integer authId;

    /**
     * The user these credentials belong to.
     *
     * <p>The owning side of a one-to-one relationship, joined via the
     * {@code user_id} foreign key. The column is non-null and unique, so each
     * user has at most one authentication record. Fetched lazily.</p>
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;

    /**
     * The hashed password for the user. Required, up to 255 characters.
     *
     * <p>Stores only the hash &mdash; never a plaintext password.</p>
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * Timestamp of the user's most recent successful login, or {@code null}
     * if they have never logged in.
     */
    @Column(name = "last_login")
    private LocalDateTime lastLogin;
}
