package com.cts.userservice.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;
/**
 * JPA entity representing a role that can be assigned to users.
 *
 * <p>Mapped to the {@code roles} table. Each role wraps a single
 * {@link RoleName} value, which is stored as its string representation and
 * constrained to be unique, so a given role name appears at most once in the
 * table.</p>
 *
 * <p>Lombok's {@code @Data} generates getters, setters, {@code equals},
 * {@code hashCode}, and {@code toString}; {@code @NoArgsConstructor} and
 * {@code @AllArgsConstructor} generate constructors (the no-arg constructor is
 * required by JPA); and {@code @Builder} provides a fluent builder.</p>
 *
 */
@Entity
@Table(name = "roles")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Role {

    /**
     * Surrogate primary key, auto-generated by the database identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "role_id")
    private Integer roleId;

    /**
     * The role's name, persisted as a unique string value.
     *
     * <p>Stored using {@link EnumType#STRING} so the readable constant name is
     * written to the database rather than its ordinal position.</p>
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role_name", nullable = false, unique = true, length = 20)
    private RoleName roleName;
}
