package com.cts.userservice.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.*;

/**
 * JPA entity representing an application user.
 *
 * <p>Mapped to the {@code users} table. Each user has a unique email address,
 * is assigned exactly one {@link Role} (a many-to-one relationship, since many
 * users may share a role), and owns an associated {@link Authentication}
 * record holding their credentials (a one-to-one relationship).</p>
 *
 * <p>The {@code authentication} association is the inverse side of the
 * relationship (mapped by {@code user} on {@link Authentication}) and cascades
 * all operations, so persisting or removing a user also persists or removes
 * its credentials.</p>
 *
 * <p>Lombok's {@code @Data} generates getters, setters, {@code equals},
 * {@code hashCode}, and {@code toString}; {@code @NoArgsConstructor} and
 * {@code @AllArgsConstructor} generate constructors (the no-arg constructor is
 * required by JPA); and {@code @Builder} provides a fluent builder.</p>
 *
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Surrogate primary key, auto-generated by the database identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long userId;

    /**
     * The user's display name. Required, up to 100 characters.
     */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * The user's email address. Required and unique across all users, used as
     * the natural login identifier. Up to 150 characters.
     */
    @Column(name = "email", nullable = false, unique = true, length = 150)
    private String email;

    /**
     * The role assigned to this user.
     *
     * <p>A many-to-one association joined via the {@code role_id} foreign key.
     * Fetched eagerly, since a user's role is almost always needed alongside
     * the user (for example, during authorization checks).</p>
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    /**
     * The authentication/credentials record owned by this user.
     *
     * <p>The inverse side of a one-to-one relationship (the owning side is
     * {@link Authentication#getUser()}). Cascades all operations and is fetched
     * lazily so credentials are loaded only when explicitly accessed.</p>
     */
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Authentication authentication;
}