server.port=9003

spring.cloud.config.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/catalog_db
spring.datasource.username=root
spring.datasource.password=kushal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost


springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ========================
# CIRCUIT BREAKER CONFIG
# ========================
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=10s


# ========================
# RETRY CONFIG
# ========================
resilience4j.retry.instances.inventoryService.maxAttempts=3
resilience4j.retry.instances.inventoryService.waitDuration=500ms


# ========================
# TIME LIMITER CONFIG
# ========================

resilience4j.timelimiter.instances.inventoryService.timeoutDuration=2s



# Logging
logging.level.com.cts.orderservice=DEBUG
