server.port=9004

spring.cloud.config.enabled=true

spring.main.allow-bean-definition-overriding=true

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=kushal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ========================
# CIRCUIT BREAKER CONFIG
# ========================

resilience4j.circuitbreaker.instances.catalogService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.catalogService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.catalogService.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=10s


# ========================
# RETRY CONFIG
# ========================

resilience4j.retry.instances.catalogService.maxAttempts=3
resilience4j.retry.instances.catalogService.waitDuration=500ms

resilience4j.retry.instances.inventoryService.maxAttempts=3
resilience4j.retry.instances.inventoryService.waitDuration=500ms


# ========================
# TIME LIMITER CONFIG
# ========================

resilience4j.timelimiter.instances.catalogService.timeoutDuration=2s
resilience4j.timelimiter.instances.inventoryService.timeoutDuration=2s



# Logging
logging.level.com.cts.orderservice=DEBUG
