package com.cts.userservice.service.impl;

import com.cts.userservice.dto.request.LoginRequest;
import com.cts.userservice.dto.request.RegisterRequest;
import com.cts.userservice.dto.request.UpdateProfileRequest;
import com.cts.userservice.dto.response.LoginResponse;
import com.cts.userservice.dto.response.UserResponse;
import com.cts.userservice.dto.response.ValidationResponse;
import com.cts.userservice.exception.customexception.AccessDeniedException;
import com.cts.userservice.exception.customexception.InvalidPasswordException;
import com.cts.userservice.exception.customexception.PasswordHashingException;
import com.cts.userservice.exception.customexception.RoleNotFoundException;
import com.cts.userservice.exception.customexception.UserAlreadyExistsException;
import com.cts.userservice.exception.customexception.UserNotFoundException;
import com.cts.userservice.model.Authentication;
import com.cts.userservice.model.Role;
import com.cts.userservice.model.RoleName;
import com.cts.userservice.model.User;
import com.cts.userservice.repository.AuthenticationRepository;
import com.cts.userservice.repository.RoleRepository;
import com.cts.userservice.repository.UserRepository;
import com.cts.userservice.security.JwtUtil;
import com.cts.userservice.service.UserService;
import java.time.LocalDateTime;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.FilterChainProxy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Default implementation of {@link UserService}.
 *
 * <p>Coordinates the user, role, and authentication repositories together with
 * password hashing and JWT generation to fulfil the service contract. User
 * profiles and their credentials are persisted in separate tables, so several
 * operations are annotated {@link Transactional} to keep those writes
 * consistent; read-only operations use {@code @Transactional(readOnly = true)}.</p>
 *
 * <p>Dependencies are injected via the constructor generated by Lombok's
 * {@code @RequiredArgsConstructor}, and the token lifetime is supplied from the
 * {@code jwt.expiration} configuration property.</p>
 */
@Service
@RequiredArgsConstructor
public class UserServiceImpl implements UserService {

    /** Repository for user records. */
    private final UserRepository userRepository;

    /** Repository for role definitions. */
    private final RoleRepository roleRepository;

    /** Spring Security filter chain (injected dependency). */
    private final FilterChainProxy springSecurityFilterChain;

    /** Repository for authentication/credential records. */
    private final AuthenticationRepository authenticationRepository;

    /** Encoder used to hash and verify passwords. */
    private final PasswordEncoder passwordEncoder;

    /** Utility for generating and parsing JWT tokens. */
    private final JwtUtil jwtUtil;

    /** Token time-to-live in milliseconds, from the {@code jwt.expiration} property. */
    @Value("${jwt.expiration}")
    private long jwtExpirationMs;

    /**
     * {@inheritDoc}
     *
     * <p>Rejects the request if a user with the same email already exists,
     * assigns the default {@link RoleName#CUSTOMER} role, persists the user,
     * then hashes the password and stores the credentials in a separate
     * {@link Authentication} record. The whole operation runs in a single
     * transaction.</p>
     *
     * @throws UserAlreadyExistsException if a user with the given email exists
     * @throws RoleNotFoundException      if the default customer role is missing
     * @throws PasswordHashingException   if password hashing fails
     */
    @Override
    @Transactional
    public UserResponse register(RegisterRequest request) {

        if (userRepository.existsByEmail(request.getEmail())) {
            throw new UserAlreadyExistsException("User already exists with email " + request.getEmail());
        }

        Role role = roleRepository.findByRoleName(RoleName.CUSTOMER)
                .orElseThrow(() -> new RoleNotFoundException("Role not found"));

        User user = User.builder()
                .name(request.getName())
                .email(request.getEmail())
                .role(role)
                .build();

        User savedUser = userRepository.save(user);

        String hash;
        try {
            hash = passwordEncoder.encode(request.getPassword());
        } catch (RuntimeException ex) {
            throw new PasswordHashingException("Password hashing failed", ex);
        }

        Authentication auth = Authentication.builder()
                .user(savedUser)
                .passwordHash(hash)
                .build();

        authenticationRepository.save(auth);

        return toUserResponse(savedUser);
    }

    /**
     * {@inheritDoc}
     *
     * <p>Looks up the user by email and their stored credentials, verifies the
     * supplied password against the stored hash, records the login timestamp,
     * and issues a JWT carrying the user's id and role.</p>
     *
     * @throws UserNotFoundException    if no user or no credentials are found
     *                                  for the given email
     * @throws InvalidPasswordException if the supplied password does not match
     */
    @Override
    @Transactional
    public LoginResponse login(LoginRequest request) {

        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new UserNotFoundException("No user found with email " + request.getEmail()));

        Authentication auth = authenticationRepository.findByUser_UserId(user.getUserId())
                .orElseThrow(() -> new UserNotFoundException("No credentials found"));

        if (!passwordEncoder.matches(request.getPassword(), auth.getPasswordHash())) {
            throw new InvalidPasswordException("Invalid password");
        }

        auth.setLastLogin(LocalDateTime.now());
        authenticationRepository.save(auth);

        RoleName roleName = user.getRole().getRoleName();
        String token = jwtUtil.generateToken(user.getUserId(), roleName);

        return LoginResponse.builder()
                .token(token)
                .userId(user.getUserId())
                .roleName(roleName)
                .build();
    }

    /**
     * {@inheritDoc}
     *
     * <p>Runs in a read-only transaction.</p>
     *
     * @throws UserNotFoundException if no user exists with the given id
     */
    @Override
    @Transactional(readOnly = true)
    public UserResponse getUserById(Long userId) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new UserNotFoundException("No user found with id " + userId));

        return toUserResponse(user);
    }

    /**
     * {@inheritDoc}
     *
     * <p>Loads the user, and if the email is being changed, ensures the new
     * email is not already taken before applying the name and email updates.</p>
     *
     * @throws UserNotFoundException      if no user exists with the given id
     * @throws UserAlreadyExistsException if the new email is already in use by
     *                                    another account
     */
    @Override
    @Transactional
    public UserResponse updateProfile(Long userId, UpdateProfileRequest request) {

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new UserNotFoundException("No user found with id " + userId));

        if (!user.getEmail().equals(request.getEmail())
                && userRepository.existsByEmail(request.getEmail())) {
            throw new UserAlreadyExistsException("Email already in use: " + request.getEmail());
        }

        user.setName(request.getName());
        user.setEmail(request.getEmail());

        User saved = userRepository.save(user);

        return toUserResponse(saved);
    }

    /**
     * {@inheritDoc}
     *
     * <p>Runs in a read-only transaction and maps each user to its public
     * response representation.</p>
     */
    @Override
    @Transactional(readOnly = true)
    public List<UserResponse> listAllUsers() {
        return userRepository.findAll()
                .stream()
                .map(this::toUserResponse)
                .toList();
    }

    /**
     * {@inheritDoc}
     *
     * <p>Assumes the request has already passed upstream authorization. Strips
     * the {@code "Bearer "} prefix from the header, extracts the user id from
     * the token, and returns it.</p>
     */
    @Override
    public ValidationResponse validate(String authHeader){
        // If request reaches here → already authorized
        String token = authHeader.substring(7);

        Long userId = Long.valueOf(jwtUtil.extractUserId(token));

        return ValidationResponse
                .builder()
                .userId(userId)
                .build();
    }


    /**
     * Maps a {@link User} entity to its public {@link UserResponse}
     * representation, exposing only safe profile fields.
     *
     * @param user the user entity to convert
     * @return the corresponding response DTO
     */
    private UserResponse toUserResponse(User user) {
        return UserResponse.builder()
                .userId(user.getUserId())
                .name(user.getName())
                .email(user.getEmail())
                .roleName(user.getRole().getRoleName())
                .build();
    }
}